export const PROJECT_MODES = Object.freeze({
  NO_PROJECT_SELECTED: "NO_PROJECT_SELECTED",
  ADDING_NEW_PROJECT: "ADDING_NEW_PROJECT",
  PROJECT_SELECTED: "PROJECT_SELECTED",
  // EDITING_PROJECT: 'EDITING_PROJECT',
  // DELETING_PROJECT: 'DELETING_PROJECT',
});
